

export const ProyectosData = [
    {id: 1,
         imagen: "public/imagenes/proyectos/proyectos1.jpg", 
         titulo: "OW + CUMULO",
    },
    {id: 2,
        imagen: "/imagenes/proyectos/proyectos2.jpg", 
        titulo: "WORK IN PROGRESS DUMONT + OW",
        },
    {id: 3,
        
        imagen: "/imagenes/proyectos/proyectos3.jpg", 
        titulo: "WORK IN PROGRESS / HOUSE IN CHAPADMALAL",
    },
    {id: 4,
        imagen: "/imagenes/proyectos/proyectos4.jpg", 
         titulo: "OW + CUMULO",
    },
    {id: 5,
        imagen: "/imagenes/proyectos/proyectos5.jpg", 
         titulo: "WORK IN PROGRESS / HOUSE IN CHAPADMALAL",
    },
    {id: 6,
        imagen: "/imagenes/proyectos/proyectos6.jpg", 
         titulo: "WORK IN PROGRESS DUMONT + OW",
    },
    {id: 7,
        imagen: "/imagenes/proyectos/proyectos7.jpg", 
         titulo: "Proyectos",
    },
    {id: 8,
        imagen: "/imagenes/proyectos/proyectos8.jpg", 
         titulo: "WORK IN PROGRESS / HOUSE IN CHAPADMALAL",
    },
    {id: 9,
        imagen: "/imagenes/proyectos/proyectos9.jpg", 
         titulo: "WORK IN PROGRESS DUMONT + OW",
    },
    {id: 10,
        imagen: "/imagenes/proyectos/proyectos10.jpg", 
        titulo: "OW + CUMULO",
    }, 
    {id: 11,
        imagen: "/imagenes/proyectos/proyectos11.jpg", 
         titulo: "WORK IN PROGRESS / HOUSE IN CHAPADMALAL",
    },
    {id: 12,
        imagen: "/imagenes/proyectos/proyectos12.jpg", 
        titulo: "OW + CUMULO",
    },
    
    
]